slam_toolbox:
  ros__parameters:
    use_sim_time: true  # Use simulation time
    map_file_name: ""  # Leave empty for online mapping
    map_start_pose: [0.0, 0.0, 0.0]  # Initial pose in the map frame [x, y, theta]
    mode: "mapping"  # Use "mapping" for online SLAM
    resolution: 0.05  # Resolution of the map in meters per cell
    max_laser_range: 30.0  # Maximum range of the laser scanner
    minimum_time_interval: 0.5  # Minimum time interval between scans
    transform_publish_period: 0.05  # Frequency of TF publishing
    map_update_interval: 2.0  # Interval for updating the map
    map_frame: "map"  # Global map frame
    odom_frame: "odom"  # Local odometry frame
    base_frame: "ego_racecar/base_link"  # Robot's base frame
    scan_topic: "/scan"  # Laser scan topic
    odom_topic: "/ego_racecar/odom"  # Specify the odometry topic
    tf_buffer_duration: 10.0  # Duration for TF buffer
    use_scan_matching: true  # Enable scan matching
    use_loop_closing: true  # Enable loop closure
    loop_closure_threshold: 0.8  # Threshold for loop closure
    loop_closure_search_radius: 8.0  # Search radius for loop closure
    queue_size: 100  # Increase the queue size for laser scan messages