# config/pure_pursuit_params.yaml
/arcus/pure_pursuit:
  ros__parameters:
    waypoints_file_path: /sim_ws/src/arcus/resources/waypoints/waypoints.csv
    drive_command_topic: /pure_pursuit/drive
    position_topic: /pf/pose/odom
    target_waypoint_topic: /target_waypoint
    costmap_topic: /local_costmap
    trajectory_risk_topic: /pure_pursuit/trajectory_risk
    error_topic: /node_error_code

    max_lookahead_distance_m: 3.5
    min_lookahead_distance_m: 0.15
    lookahead_distance_gain: 0.40
    
    risk_lookahead_gain: 0.6
    ttc_decay_rate: 1.0
    min_ttc_speed_mps: 0.30

    max_lookahead_fraction_of_path: 0.05
    loop_frequency_hz: 38.0
    wheelbase_m: 0.325
    
    speed_min: 0.3
    speed_max: 8.0
    a_lat_max: 2.4
    a_accel_max: 9.0
    a_brake_max: 7.5
    speed_eps: 1e-6
